#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Docopt\Docopt;

$usage = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)

Options:
  -h --help                     Show this screen
  -v --version                  Show version
DOC;

try {
    $arguments = new Docopt($usage, ['version' => 'Gendiff 0.1']);
    $args = $arguments->handle(array_slice($_SERVER['argv'], 1));

    if ($args['--help']) {
        echo $usage . "\n";
        exit(0);
    }

    if ($args['--version']) {
        echo "Gendiff 0.1\n";
        exit(0);
    }

} catch (\Docopt\ExitException $e) {
    echo $e->getMessage();
}
