name: CI
on: push
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'
          coverage: xdebug
      - run: make install
      - name: List files in fixtures directory
        run: ls -l /home/runner/work/php-project-48/php-project-48/tests/fixtures
      - run: make lint
      - run: make test-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
